### ISSUE TITLE
Discord rich presence isn't there

### ISSUE THREAD

**Issue by SwiftWinds** [izyumidev/xcode-discord-rpc#2]
I have a project open:

<img width="1440" alt="image" src="https://github.com/izyumidev/xcode-discord-rpc/assets/12981958/72f841ab-6733-4699-af6d-1a373d5ea8e2">

But there is no status:

![image](https://github.com/izyumidev/xcode-discord-rpc/assets/12981958/281177e3-a8f0-43cf-8d75-dff2e13e4eab)

Any help?

Thanks :)

**Comment by izyumidev** [comment]
Thank you for reporting. I will take a look into this.

**Comment by izyumidev** [comment]
@SwiftWinds Could you run `brew services list` in your terminal to verify that xcode-discord-rpc is running?

**Comment by SwiftWinds** [comment]
<img width="705" alt="image" src="https://github.com/izyumidev/xcode-discord-rpc/assets/12981958/b3344031-2993-498e-b586-d36db110c4ec">
Looks like there is an error

**Comment by SwiftWinds** [comment]
<img width="701" alt="image" src="https://github.com/izyumidev/xcode-discord-rpc/assets/12981958/a59e46bf-50c3-4145-ade5-69041aacf11c">
Seems like there are no logs...?

**Comment by izyumidev** [comment]
There are few things I can think of that could fix this.
- try upgrading xcode-discord-rpc
- try [uninstalling](/usr/local/var/log/hombebrew/xcode-discord-rpc)

If those don't do any good. Let me know.

P.S. Logs should be in those files in your screenshot `homebrew.mxcl.xcode-discord-rpc.log` and `homebrew.mxcl.xcode-discord-rpc.stderr.log`.

**Comment by SwiftWinds** [comment]
I tried upgrading but it was already latest:

<img width="694" alt="image" src="https://github.com/izyumidev/xcode-discord-rpc/assets/12981958/94c0dc33-8fda-4f34-aa3d-42da3ba6efec">

Then, I uninstalled:

<img width="684" alt="image" src="https://github.com/izyumidev/xcode-discord-rpc/assets/12981958/62675438-77d5-4a99-9a2c-6dd1fa2d9077">

And reinstalled:

<img width="706" alt="image" src="https://github.com/izyumidev/xcode-discord-rpc/assets/12981958/0922844b-52bc-4c9d-855a-51ecd19362e7">

However, there was still an error:

<img width="706" alt="image" src="https://github.com/izyumidev/xcode-discord-rpc/assets/12981958/d8204742-9f1b-492b-9a13-c1c17962838a">

And both log files are empty:

<img width="705" alt="image" src="https://github.com/izyumidev/xcode-discord-rpc/assets/12981958/202bd7ea-15c4-4f90-aa74-4ee3f62d3ae3">

Any advice?

**Comment by izyumidev** [comment]
Could you try running `brew services stop xcode-discord-rpc` to stop it, then start it again with `brew services start xcode-discord-rpc`? Also, list brew services between each command.

**Comment by izyumidev** [comment]
I have just released v0.1.4. Could you try to uninstall then install, once again?

**Comment by izyumidev** [comment]
I will close the issue for a lack of response.

**Comment by SwiftWinds** [comment]
Hey forgot to reply but after installing the release `v0.1.4`, it works. Thanks!

**Comment by royalgraphx** [comment]
I did not mean to reference this GH Issue, forgive the bump. It was accidentally referenced when adding a hastag 2 for "second take"

**Comment by SwiftWinds** [comment]
No worries!
