### ISSUE TITLE
bug: high CPU usage

### ISSUE THREAD

**Issue by blackxfiied** [izyumidev/xcode-discord-rpc#3]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/izyumidev/xcode-discord-rpc/issues) that already report this problem, without success.

### Version

0.1.4

### Current Behavior

the cpu usage gets pretty high and drains battery when discord isn't open

### Expected Behavior

the cpu usage shouldn't be that high

### Steps to Reproduce

1. enable brew service of xcode discord rpc
2. wait a while after discord is either stuck loading or closed
3. cpu usage goes high and kills battery

**Comment by izyumidev** [comment]
Thank you for reporting this. I will try to find ways to reduce CPU and battery usage, especially when Xcode isn't running.

**Comment by izyumidev** [comment]
Please take a look at release [v0.1.6](https://github.com/izyumidev/xcode-discord-rpc/releases/tag/v0.1.6). I've increased the wait time from 5 seconds to 30 seconds. This should somewhat reduce the CPU usage.

**Comment by blackxfiied** [comment]
The CPU usage has gone down substantially since 0.1.6.
Even with an M1 Pro, it was struggling to keep up haha 😅
thanks for all you do, man this plugin fills a gap the xcode community needed

**Comment by izyumidev** [comment]
@blackxfiied Thank you for the kind words and the star!!
